import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/user_model.dart';
import '../models/apartment_model.dart';
import '../models/flat_model.dart';
import '../models/president_invitation_model.dart';
import '../core/theme/role_theme.dart';
import '../core/services/firestore_service.dart';
import '../core/services/firebase_auth_service.dart';
import 'notification_provider.dart';

class RegistrationProvider extends ChangeNotifier {
  final FirestoreService    _fs          = FirestoreService();
  final FirebaseAuthService _authService = FirebaseAuthService();

  bool    _isLoading = false;
  String? _error;

  bool    get isLoading => _isLoading;
  String? get error     => _error;

  void clearError() {
    _error = null;
    notifyListeners();
  }

  // ── President self-registration (Primary — creates apartment + account) ────

  Future<({UserModel? user, String? aptCode, String? error})>
      selfRegisterPresident({
    required String name,
    required String email,
    required String phone,
    required String password,
    required String apartmentName,
    required String apartmentType,
    required String address,
    required int    totalFlats,
    required int    towerCount,
    required List<String> towerNames,
    required String presidentFlat,
  }) async {
    _isLoading = true;
    _error     = null;
    notifyListeners();

    try {
      // 1. Duplicate apartment check (name + address + type)
      final isDuplicate = await _fs.apartmentExists(
        name:    apartmentName.trim(),
        address: address.trim(),
        type:    apartmentType,
      );
      if (isDuplicate) {
        return _fail('An apartment with this name and address already exists.');
      }

      // 2. Collision-safe unique apartment code
      final aptCode = await _fs.generateUniqueApartmentCode(apartmentName);
      final aptId   = 'apt_${DateTime.now().millisecondsSinceEpoch}';

      // 3. Create Auth account + apartment doc + user doc (atomic batch)
      final result = await _authService.selfRegisterPresident(
        name:          name.trim(),
        email:         email.trim().toLowerCase(),
        phone:         phone.trim(),
        password:      password,
        apartmentId:   aptId,
        apartmentCode: aptCode,
        apartmentName: apartmentName.trim(),
        apartmentType: apartmentType,
        address:       address.trim(),
        totalFlats:    totalFlats,
        towerCount:    towerCount,
        towerNames:    towerNames,
        presidentFlat: presidentFlat.trim(),
      );

      if (result.error != null) {
        return _fail(result.error!);
      }

      // 4. Auto-generate all flats (with president flat reserved + UID set)
      final uid   = result.user!.id;
      final flats = generateFlatsForApartment(
        apartmentId:         aptId,
        totalFlats:          totalFlats,
        isGated:             apartmentType == 'Gated Community',
        towerCount:          towerCount,
        towerNames:          towerNames,
        presidentFlatNumber: presidentFlat.trim(),
        presidentUid:        uid,
      );
      await _fs.createFlats(flats);

      _isLoading = false;
      notifyListeners();
      return (user: result.user, aptCode: aptCode, error: null);
    } catch (e) {
      return _fail('An error occurred. Please try again.');
    }
  }

  // ── President activation (Secondary — activates super-admin-created apt) ──

  Future<({UserModel? user, ApartmentModel? apt, String? error})>
      registerPresident({
    required String email,
    required String password,
    required String apartmentCode,
    required String unit,
    required NotificationProvider notifProvider,
  }) async {
    _isLoading = true;
    _error     = null;
    notifyListeners();

    final apt =
        await _fs.findApartmentByCode(apartmentCode.trim().toUpperCase());
    if (apt == null) {
      return _failApt('Invalid Apartment Code. Please check and try again.');
    }
    if (apt.status == 'active') {
      return _failApt('This apartment already has a registered president.');
    }
    if (apt.status == 'disabled') {
      return _failApt('This apartment is currently disabled.');
    }

    final emailTrimmed = email.trim().toLowerCase();
    if (apt.presidentEmail?.toLowerCase() != emailTrimmed) {
      return _failApt(
          'This email is not authorized for President registration for this apartment.');
    }

    final result = await _authService.registerPresident(
      email:    emailTrimmed,
      password: password,
      apt:      apt,
      unit:     unit.trim(),
    );

    if (result.error != null) {
      return _failApt(result.error!);
    }

    final uid = result.user!.id;

    // Update president flat's residentId (flat was pre-generated by super admin)
    final presFlat = apt.presidentFlat;
    if (presFlat != null && presFlat.isNotEmpty) {
      final flatDoc = await _fs.getFlatByNumber(apt.id, presFlat);
      if (flatDoc != null) {
        await _fs.updateFlat(flatDoc.id, {
          'residentId':   uid,
          'residentType': 'President',
          'updatedAt':    Timestamp.fromDate(DateTime.now()),
        });
      }
    }

    // Notify all super admins
    await notifProvider
        .addAndPersistNotification(
          title:      'New President Registered',
          body:
              '${apt.presidentName ?? 'A president'} has joined ${apt.name} as President.',
          type:       'president_registered',
          targetRole: UserRole.superAdmin,
        )
        .catchError(
            (e) => debugPrint('[NOTIF] president_registered error: $e'));

    _isLoading = false;
    notifyListeners();
    return (user: result.user, apt: apt, error: null);
  }

  // ── Resident direct registration ──────────────────────────────────────────

  /// Validates apartment code → finds & verifies flat is available →
  /// checks email + phone uniqueness → creates account → reserves flat →
  /// sends email verification.
  ///
  /// Returns (user, apt, error). error is null on success.
  Future<({UserModel? user, ApartmentModel? apt, String? error})>
      registerResident({
    required String name,
    required String email,
    required String phone,
    required String password,
    required String apartmentCode,
    required String flatNumber,
  }) async {
    _isLoading = true;
    _error     = null;
    notifyListeners();

    try {
      // 1. Find apartment
      final apt =
          await _fs.findApartmentByCode(apartmentCode.trim().toUpperCase());
      if (apt == null) {
        return _failApt('Invalid Apartment Code. Please check and try again.');
      }
      if (apt.status != 'active') {
        return _failApt(
            'This apartment is not yet active. Please contact the president.');
      }

      // 2. Find flat → must exist and be available
      final flat = await _fs.getFlatByNumber(apt.id, flatNumber.trim());
      if (flat == null) {
        return _failApt(
            'Flat "$flatNumber" was not found in this apartment. Please check the flat number.');
      }
      if (!flat.isAvailable) {
        return _failApt(
            'Flat "$flatNumber" is already occupied. Please contact your president.');
      }

      final emailTrimmed = email.trim().toLowerCase();
      final phoneTrimmed = phone.trim();

      // 3. Email uniqueness
      final existingUid = await _fs.uidForEmail(emailTrimmed);
      if (existingUid != null) {
        return _failApt('This email is already registered.');
      }

      // 4. Phone uniqueness
      final phoneInUse = await _fs.phoneExists(phoneTrimmed);
      if (phoneInUse) {
        return _failApt('This mobile number is already registered.');
      }

      // 5. Create Auth account + users doc + reserve flat (atomic)
      final authResult = await _authService.registerResident(
        name:        name.trim(),
        email:       emailTrimmed,
        phone:       phoneTrimmed,
        password:    password,
        apartmentId: apt.id,
        flatId:      flat.id,
        flatNumber:  flat.flatNumber,
      );

      if (authResult.error != null) {
        return _failApt(authResult.error!);
      }

      _isLoading = false;
      notifyListeners();
      return (user: authResult.user, apt: apt, error: null);
    } catch (e) {
      return _failApt('An error occurred. Please try again.');
    }
  }

  /// Reloads the Firebase Auth user and checks emailVerified status.
  Future<bool> checkEmailVerified() async {
    try {
      await _authService.firebaseUser?.reload();
      return _authService.firebaseUser?.emailVerified ?? false;
    } catch (_) {
      return false;
    }
  }

  /// Sends a new verification email to the currently signed-in user.
  Future<void> resendVerificationEmail() async {
    try {
      await _authService.firebaseUser?.sendEmailVerification();
    } catch (_) {}
  }

  /// Signs out the current user — used when user cancels from verification sheet.
  Future<void> abortRegistration() async {
    await _authService.signOut();
  }

  // ── Welcome email trigger ─────────────────────────────────────────────────

  /// Sets `welcomeEmailReady: true` on the user doc AFTER email verification.
  /// The Cloud Function `onWelcomeEmailReady` watches this field and sends the
  /// welcome email exactly once (guarded by `welcomeEmailSentAt`).
  Future<void> setWelcomeEmailReady(String userId) async {
    try {
      await _fs.setWelcomeEmailReady(userId);
    } catch (e) {
      debugPrint('[REG] setWelcomeEmailReady failed: $e');
    }
  }

  // ── Invitation-based president activation ─────────────────────────────────

  /// Validates a president invitation token.
  /// Returns (invitation, error). error is null on success.
  Future<({PresidentInvitationModel? invitation, String? error})>
      validateInvitationToken(String token) async {
    _isLoading = true;
    _error     = null;
    notifyListeners();

    try {
      final invitation = await _fs.getInvitationByToken(token);
      _isLoading = false;
      notifyListeners();

      if (invitation == null) {
        return _failInvitation('Invalid activation token. Please check and try again.');
      }
      if (invitation.isCompleted) {
        return _failInvitation('This invitation has already been used.');
      }
      if (invitation.isExpired) {
        return _failInvitation(
          'Your invitation has expired. Please contact your Super Admin.',
        );
      }
      return (invitation: invitation, error: null);
    } catch (e) {
      _isLoading = false;
      notifyListeners();
      return _failInvitation('Failed to validate token. Please try again.');
    }
  }

  /// Step 1 of president activation:
  ///   Creates a Firebase Auth account and sends email verification.
  ///   No Firestore records are created yet — those happen in [completePresidentActivation].
  /// Returns (uid, error). error is null on success.
  Future<({String? uid, String? error})> beginPresidentActivation({
    required PresidentInvitationModel invitation,
    required String password,
  }) async {
    _isLoading = true;
    _error     = null;
    notifyListeners();

    // Re-validate invitation freshness before creating an Auth account
    if (invitation.isCompleted) {
      return _failUid('This invitation has already been used.');
    }
    if (invitation.isExpired) {
      return _failUid('Your invitation has expired. Please contact your Super Admin.');
    }

    final result = await _authService.createAndVerifyAccount(
      email:    invitation.presidentEmail,
      password: password,
    );

    _isLoading = false;
    notifyListeners();

    if (result.error != null) return _failUid(result.error!);
    return (uid: result.uid, error: null);
  }

  /// Step 2 of president activation (called after email verification confirmed):
  ///   • Creates the Firestore user doc
  ///   • Activates the apartment
  ///   • Marks the invitation as completed
  ///   • Updates the president flat
  ///   • Signals the welcome email via [setWelcomeEmailReady]
  ///
  /// On failure the Firebase Auth account is deleted to prevent orphans.
  /// Returns (user, error). error is null on success.
  Future<({UserModel? user, String? error})> completePresidentActivation({
    required PresidentInvitationModel invitation,
    required String uid,
  }) async {
    _isLoading = true;
    _error     = null;
    notifyListeners();

    try {
      // Atomic batch: users doc + apartment + invitation
      await _fs.activatePresidentBatch(uid: uid, invitation: invitation);

      // Update flat (separate read-then-write — acceptable for this step)
      final flat = await _fs.getFlatByNumber(
          invitation.apartmentId, invitation.presidentFlatNumber);
      if (flat != null) {
        await _fs.updateFlat(flat.id, {
          'residentId':   uid,
          'residentType': 'President',
          'status':       'occupied',
          'updatedAt':    Timestamp.fromDate(DateTime.now()),
        });
      }

      // Trigger welcome email (Cloud Function sends it after this field is set)
      await _fs.setWelcomeEmailReady(uid);

      final user = await _fs.getUser(uid);
      _isLoading = false;
      notifyListeners();
      return (user: user, error: null);
    } catch (e) {
      // Rollback: delete the Auth account to avoid orphans
      await _authService.deleteCurrentUser();
      return _failUser('Activation failed. Please try again.');
    }
  }

  // ── Internal helpers ──────────────────────────────────────────────────────

  ({UserModel? user, String? aptCode, String? error}) _fail(String msg) {
    _error     = msg;
    _isLoading = false;
    notifyListeners();
    return (user: null, aptCode: null, error: msg);
  }

  ({UserModel? user, ApartmentModel? apt, String? error}) _failApt(String msg) {
    _error     = msg;
    _isLoading = false;
    notifyListeners();
    return (user: null, apt: null, error: msg);
  }

  ({PresidentInvitationModel? invitation, String? error}) _failInvitation(String msg) {
    _error     = msg;
    _isLoading = false;
    notifyListeners();
    return (invitation: null, error: msg);
  }

  ({String? uid, String? error}) _failUid(String msg) {
    _error     = msg;
    _isLoading = false;
    notifyListeners();
    return (uid: null, error: msg);
  }

  ({UserModel? user, String? error}) _failUser(String msg) {
    _error     = msg;
    _isLoading = false;
    notifyListeners();
    return (user: null, error: msg);
  }
}
