# =============================================================================
# Maintify — ProGuard / R8 rules
# =============================================================================
# Full R8 mode: shrinking + optimization + obfuscation + resource shrinking.
# Keep rules below protect Flutter, Firebase, Google Play Services, and
# reflection-dependent plugin code from being removed or renamed.
# =============================================================================

# ---------- Attributes (required for crash reporting & debugging) -------------
-keepattributes SourceFile,LineNumberTable
-keepattributes *Annotation*
-keepattributes Signature
-keepattributes InnerClasses,EnclosingMethod
-renamesourcefileattribute SourceFile

# ---------- Flutter ----------------------------------------------------------
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }
-keep class io.flutter.embedding.** { *; }
-keep class io.flutter.plugin.** { *; }

# ---------- Firebase ---------------------------------------------------------
# Firebase SDKs ship with embedded consumer rules; these are belt-and-suspenders.
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class com.google.firebase.messaging.** { *; }

# ---------- Hive -------------------------------------------------------------
-keep class com.hivedb.** { *; }

# ---------- Application ------------------------------------------------------
-keep class com.maintify.app.** { *; }

# ---------- R values (accessed by name in plugins) ---------------------------
-keepclassmembers class **.R$* {
    public static <fields>;
}

# ---------- Missing-class suppressions (auto-generated by R8) ----------------
# Flutter Play Store deferred components (not used by this app)
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task
# gRPC legacy OkHttp adapter (optional dependency not on classpath)
-dontwarn com.squareup.okhttp.CipherSuite
-dontwarn com.squareup.okhttp.ConnectionSpec
-dontwarn com.squareup.okhttp.TlsVersion
# Guava reflection (not needed at runtime)
-dontwarn java.lang.reflect.AnnotatedType
